"""followers

Revision ID: 80968639b2be
Revises: f363926e29b6
Create Date: 2018-04-24 12:03:41.392620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80968639b2be'
down_revision = 'f363926e29b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
